{{- if .Values.server.ingress }}
{{- with .Values.server.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "teamcity.server.fullname" $ }}
  labels:
    {{- include "teamcity.server.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .className }}
  {{- if .tls }}
  tls:
{{ toYaml .tls | indent 4 }}
  {{- end }}
  {{- if .rules }}
  rules:
{{ toYaml .rules | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
