apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teamcity.agent.fullname" . }}
  labels:
    {{- include "teamcity.agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.teamcity.agent.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "teamcity.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "teamcity.agent.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: teamcity-agent
          image: "{{ .Values.teamcity.agent.image.repository }}:{{ .Values.teamcity.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.teamcity.agent.image.pullPolicy }}
{{- if .Values.teamcity.agent.env }}
          env:
{{ toYaml .Values.teamcity.agent.env | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.teamcity.agent.resources | indent 12 }}
{{- if .Values.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
      restartPolicy: Always
{{- if .Values.volumes }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
{{- end }}
