apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "teamcity.agent.fullname" $ }}
  labels:
    {{- include "teamcity.agent.labels" $ | nindent 4 }}
spec:
  {{- with .Values.agent }}
  {{- $agent := . }}
  ordinals:
    start: {{ .ordinals.start | default 1 }}
  replicas: {{ .replicaCount | default 1 }}
  serviceName: {{ include "teamcity.agent.fullname" $ }}
  selector:
    matchLabels:
      {{- include "teamcity.agent.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "teamcity.agent.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
        {{- with .containers.agent }}
        - name: teamcity-agent
          {{- with .image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}{{ if .tagSuffix }}-{{ .tagSuffix }}{{ end }}"
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          {{- end }}
          env:
            - name: AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- if .env }}
          {{ toYaml .env | nindent 12 }}
          {{- end }}
          {{- if .resources }}
          resources:
          {{ toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if .securityContext }}
          securityContext:
          {{ toYaml .securityContext | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
          {{ toYaml .volumeMounts | nindent 12 }}
          {{- end }}
          {{- end }}
      hostname: {{ .hostname }}
      restartPolicy: Always
      {{- if .volumes }}
      {{- if .serviceAccountName }}
      serviceAccountName: {{ .serviceAccountName }}
      {{- end }}
      volumes:
      {{ toYaml .volumes | nindent 8 }}
      {{- end }}
  {{- if .volumeClaimTemplates }}
  volumeClaimTemplates:
  {{ toYaml .volumeClaimTemplates | nindent 4 }}
  {{- end }}
  {{- end }}
