apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity.agent.fullname" . }}
  labels:
    {{- include "teamcity.agent.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "teamcity.agent.selectorLabels" . | nindent 4 }}
