{{- if .Values.server.services }}
{{- range .Values.server.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity.server.fullname" $ }}{{ if .name }}-{{ .name }}{{ end }}
  labels: {{- include "teamcity.server.labels" $ | nindent 4 }}
spec:
  selector: {{- include "teamcity.server.selectorLabels" $ | nindent 4 }}
  type: {{ .type }}
  {{- if .ports }}
  ports: {{- toYaml .ports | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
