{{- if .Values.server.service }}
{{- with .Values.server.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity.server.fullname" $ }}
  labels:
    {{- include "teamcity.server.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "teamcity.server.selectorLabels" $ | nindent 4 }}
  type: {{ .type }}
  {{- if .ports }}
  ports:
{{ toYaml .ports | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
